CardGames.MVC/Models/CardGames/Edition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CardGames.MVC.Models.CardGames
{
    public class Edition
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ReleaseYear { get; set; }

        public int GameId { get; set; }
        public virtual Game Game { get; set; }

        public int EditionCardListId { get; set; }
        public virtual EditionCardList EditionCardList { get; set; }
    }
}

CardGames.MVC/Controllers/CardsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CardGames.MVC.Models.CardGames;

namespace CardGames.MVC.Controllers
{
    public class CardsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Cards/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }
            var cardInList = card.CardInCardLists.FirstOrDefault(l => l.CardList is EditionCardList);
            return View(cardInList);
        }

        // GET: Cards/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Edition = db.Editions.Find(id);
            return View();
        }

        // POST: Cards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EditionId,Name,Description,Number")] CardViewModel cardViewModel)
        {
            var edition = db.Editions.Find(cardViewModel.EditionId);
            ViewBag.Edition = edition;
            if (ModelState.IsValid)
            {
                var card = db.Cards.Create();
                card.Name = cardViewModel.Name;
                card.Description = cardViewModel.Description;
                db.SaveChanges();

                db.Cards.Add(card);

                var cardInList = edition.EditionCardList.AddCard(card, 1, cardViewModel.Number);

                //db.Entry(cardInList).State = EntityState.Modified; 

                db.SaveChanges();
                return RedirectToAction("Details", "Editions", new { id = edition.Id });
            }

            return View(cardViewModel);
        }

        // GET: Cards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }
            var cardInList = card.CardInCardLists.FirstOrDefault(l => l.CardList is EditionCardList);
            var cardViewModel = new CardViewModel
            {
                CardId = card.Id,
                Description = card.Description,
                Name = card.Name,
                EditionId = ((EditionCardList)cardInList.CardList).Edition.Id,
                Number = cardInList.Number
            };
            return View(cardViewModel);
        }

        // POST: Cards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CardId,Name,Description,Number,EditionId")] CardViewModel cardViewModel)
        {
            if (ModelState.IsValid)
            {
                var card = db.Cards.Find(cardViewModel.CardId);
                card.Name = cardViewModel.Name;
                card.Description = cardViewModel.Description;

                var cardInList = card.CardInCardLists.First(cl => cl.CardList is EditionCardList);
                cardInList.Number = cardViewModel.Number;

                //db.Entry(card).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Editions", new { id = cardViewModel.EditionId});
            }
            return View(cardViewModel);
        }

        // GET: Cards/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Cards.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }
            return View(card);
        }

        // POST: Cards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Card card = db.Cards.Find(id);
            var edition = card.Edition;
            db.Cards.Remove(card);
            db.SaveChanges();
            return RedirectToAction("Details", "Editions", new {id = edition.Id});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CardGames.MVC/Controllers/EditionsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CardGames.MVC.Models.CardGames;

namespace CardGames.MVC.Controllers
{
    public class EditionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Editions
        public ActionResult Index()
        {
            var editions = db.Editions.Include(e => e.EditionCardList).Include(e => e.Game);
            return View(editions.ToList());
        }

        // GET: Editions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Edition edition = db.Editions.Find(id);
            if (edition == null)
            {
                return HttpNotFound();
            }
            return View(edition);
        }

        // GET: Editions/Create/:id
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Game = db.Games.FirstOrDefault(g => g.Id == id);
            return View();
        }

        // POST: Editions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,ReleaseYear,GameId")] Edition edition)
        {
            if (ModelState.IsValid)
            {
                edition.EditionCardList = new EditionCardList {Name = edition.Name};
                db.Editions.Add(edition);
                db.SaveChanges();
                return RedirectToAction("Details", "Games", new {id = edition.GameId});
            }

            return Create(edition.GameId);
        }

        // GET: Editions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Edition edition = db.Editions.Find(id);
            if (edition == null)
            {
                return HttpNotFound();
            }
            ViewBag.EditionCardListId = new SelectList(db.CardLists, "Id", "Name", edition.EditionCardListId);
            ViewBag.GameId = new SelectList(db.Games, "Id", "Name", edition.GameId);
            return View(edition);
        }

        // POST: Editions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ReleaseYear,GameId")] Edition edition)
        {
            if (ModelState.IsValid)
            {
                var e = db.Editions.Find(edition.Id);
                e.GameId = edition.GameId;
                e.Name = edition.Name;
                e.ReleaseYear = edition.ReleaseYear;
                db.Entry(e).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Games", new { id = edition.GameId });
            }
            ViewBag.GameId = new SelectList(db.Games, "Id", "Name", edition.GameId);
            return View(edition);
        }

        // GET: Editions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Edition edition = db.Editions.Find(id);
            if (edition == null)
            {
                return HttpNotFound();
            }
            return View(edition);
        }

        // POST: Editions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Edition edition = db.Editions.Find(id);
            db.Editions.Remove(edition);
            db.SaveChanges();
            return RedirectToAction("Details", "Games", new { id = edition.GameId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CardGames.MVC/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CardGames.MVC;
using CardGames.MVC.Models.CardGames;

namespace CardGames.MVC.Controllers
{
    public class GamesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Games
        public ActionResult Index()
        {
            return View(db.Games.ToList());
        }

        // GET: Games/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // GET: Games/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ReleaseYear")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Games.Add(game);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(game);
        }

        // GET: Games/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ReleaseYear")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Entry(game).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(game);
        }

        // GET: Games/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Game game = db.Games.Find(id);
            db.Games.Remove(game);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CardGames.MVC/Views/Editions/Create.cshtml
@model CardGames.MVC.Models.CardGames.Edition

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edition</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GameId, "GameId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GameId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GameId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CardGames.MVC/Views/Editions/Delete.cshtml
@model CardGames.MVC.Models.CardGames.Edition

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Edition</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EditionCardList.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EditionCardList.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Game.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Game.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Details", "Games", new { id = Model.GameId }, null)
        </div>
    }
</div>

CardGames.MVC/Views/Editions/Details.cshtml
@model CardGames.MVC.Models.CardGames.Edition

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Edition</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            Game
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Game.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>

    </dl>
</div>

<h3>Card List</h3>

<p>
    @Html.ActionLink("Create new card", "Create", "Cards", new {id = Model.Id}, null)
</p>

<table class="table">
    <tr>
        <th>Number</th>
        <th>Name</th>
        <th></th>
    </tr>

    @foreach (var item in Model.EditionCardList.CardInCardLists)
    {
        <tr>
            <td>@item.Number</td>
            <td>@item.Card.Name</td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Cards", new {id = item.CardId}, null) |
                @Html.ActionLink("Details", "Details", "Cards", new {id = item.CardId}, null) |
                @Html.ActionLink("Delete", "Delete", "Cards", new {id = item.CardId}, null)
            </td>
        </tr>
    }

</table>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Details", "Games", new { id = Model.GameId }, null)
</p>

CardGames.MVC/Views/Editions/Edit.cshtml
@model CardGames.MVC.Models.CardGames.Edition

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edition</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GameId, "GameId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GameId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GameId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details", "Games", new {id = Model.GameId}, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CardGames.MVC/Views/Editions/Index.cshtml
@model IEnumerable<CardGames.MVC.Models.CardGames.Edition>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EditionCardList.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Game.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EditionCardList.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Game.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseYear)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>